config/routes.rb
Rails.application.routes.draw do
  
  resources :top, only: :index

  resources :users
  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
     @users = User.all
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<h2>記事ページ</h2>

<% if @articles.present? %>
  <table class="list">
    <tr>
      <th>タイトル</th>
      <th>本文</th>
      <th>閲覧制限</th>
    </tr>
    <% @articles.each do |article|%>
      <tr>
        <td><%= article.title %><td>
        <td><%= article.body %><td>
        <td><%= article.member_onle %><td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>記事情報がありません。</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curriculum2</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
      <div id="header">
        <%= render "shared/header" %>
      </div>

      <%= yield %>
      
    </div>
    <div id="footer">
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<%= link_to "このサイトについて", '#' %> |
Copyright (C) <%= link_to "HIGHTWO Corporation.", "http://www.hightwo.co.jp/" %>
2018

app/views/shared/_header.html.erb
<%= image_tag("logo.gif", size: "120x120", alt: "logo Image") %>

<div class="menubar">
  <%= link_to "TOP", top_index_path %> &nbsp;|&nbsp;
  <%= link_to "ニュース", "#" %> &nbsp;|&nbsp;
  <%= link_to "ブログ", "#" %> &nbsp;|&nbsp;
  <%= link_to "会員名簿", "#" %> &nbsp;|&nbsp;
  <%= link_to "管理ページ", "#" %>
</div>

app/views/shared/_sidebar.html.erb
<div id='sidebar'>
  <h2>最新ニュース</h2>
  <ul>
    <% 5.times do |i| %>
      <li><%= link_to "ニュースの見出し", "#" %></li>
    <% end %>
  </ul>
  <h2>会員のブログ</h2>
  <ul>
    <% 5.times do |i| %>
      <li><%= link_to "ブログの見出し", "#" %></li>
    <% end %>
  </ul>
</div>

app/views/top/index.html.erb
<div id='content'>
  <% 5.times do |x| %>
    <h2>見出し</h2>
    <p>ここに本文が入ります。ここに本文が入ります。ここに本文が入ります。ここに本文が入ります。
    <%= link_to "もっと読む", "#" %></p>
  <% end %>
</div>

<%= render 'shared/sidebar' %>

app/views/users/index.html.erb
<h2>会員ページ</h2>

<% if @users.present? %>
  <table class="list">
    <tr>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>性別</th>
      <th>生年月日</th>
    </tr>
    <% @users.each do |user|%>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= user.birth_day %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>会員情報がありません。</p>
<% end %>